use FestivalMeetUp
GO

DROP TABLE Posts;
DROP TABLE Feeds;
DROP TABLE User_Reports;
DROP TABLE Event_Reports;
DROP TABLE User_Report_Types;
DROP TABLE Event_Report_Types;
DROP TABLE Participating_Users;
DROP TABLE Events;
DROP TABLE Addresses;
DROP TABLE Accounts;
DROP TABLE Users;

CREATE TABLE Users
(
	ID				BIGINT NOT NULL PRIMARY KEY,
	Facebook		VARCHAR(300),
	Instagram		VARCHAR(300),
);

CREATE TABLE Accounts
(
	Username		VARCHAR(100) NOT NULL PRIMARY KEY,
	Password_Hash	VARCHAR(100) NOT NULL, 
	User_ID			BIGINT NOT NULL FOREIGN KEY REFERENCES Users(ID)
);

CREATE TABLE Addresses
(
	ID				BIGINT NOT NULL PRIMARY KEY,
	Country			VARCHAR(50),
	County			VARCHAR(50),
	City			VARCHAR(50),
	Street			VARCHAR(150),
	Number			INT,
	ZIP				VARCHAR(6)
);

CREATE TABLE Events
(
	ID				BIGINT NOT NULL PRIMARY KEY,
	Creator_User	BIGINT NOT NULL FOREIGN KEY REFERENCES Users(ID),
	Event_Address	BIGINT NOT NULL FOREIGN KEY REFERENCES Addresses(ID),
	Starting_Date	DATETIME NOT NULL,
	Ending_Date		DATETIME NOT NULL
);

CREATE TABLE Participating_Users
(
	User_ID			BIGINT NOT NULL FOREIGN KEY REFERENCES Users(ID),
	Event_ID		BIGINT NOT NULL FOREIGN KEY REFERENCES Events(ID),
);

CREATE TABLE Event_Report_Types
(
	ID				BIGINT NOT NULL PRIMARY KEY,
	Name			VARCHAR(50)
);

CREATE TABLE Event_Reports
(
	ID				BIGINT NOT NULL PRIMARY KEY,
	Submitter		BIGINT NOT NULL FOREIGN KEY REFERENCES Users(ID),
	Target_Event	BIGINT NOT NULL FOREIGN KEY REFERENCES Events(ID),
	Report_Type		BIGINT NOT NULL FOREIGN KEY REFERENCES Event_Report_Types(ID),
	Details			VARCHAR(1000)
);

CREATE TABLE User_Report_Types
(
	ID				BIGINT NOT NULL PRIMARY KEY,
	Name			VARCHAR(50)
);

CREATE TABLE User_Reports
(
	ID				BIGINT NOT NULL PRIMARY KEY,
	Submitter		BIGINT NOT NULL FOREIGN KEY REFERENCES Users(ID),
	Target_User		BIGINT NOT NULL FOREIGN KEY REFERENCES Users(ID),
	Report_Type		BIGINT NOT NULL FOREIGN KEY REFERENCES User_Report_Types(ID),
	Details			VARCHAR(1000)
);

CREATE TABLE Feeds
(
	ID				BIGINT NOT NULL PRIMARY KEY,
	Event_ID		BIGINT NOT NULL FOREIGN KEY REFERENCES Events(ID),
);

CREATE TABLE Posts
(
	ID				BIGINT NOT NULL PRIMARY KEY,
	Feed_ID			BIGINT NOT NULL FOREIGN KEY REFERENCES Feeds(ID),
	Post_Text		VARCHAR(500)
);